# name: Deploy to Staging

# on:
#   push:
#     branches: [ dev ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - run: npm i
#     - run: gulp build
#     - name: rsync deployments
#       uses: burnett01/rsync-deployments@4.0
#       with:
#         switches: -avzr --delete --exclude-from='deploy-exclude.txt'
#         path: ./
#         remote_path: ${{ secrets.SERVER_DIR_DEV }}
#         remote_host: ${{ secrets.SERVER_DESTINATION_DEV }}
#         remote_port: ${{ secrets.SERVER_PORT_DEV }}
#         remote_user: ${{ secrets.USERNAME_DEV }}
#         remote_key: ${{ secrets.SERVER_SSH_KEY }}
