name: Deploy to Public

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm i
    - run: gulp build
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.0
      with:
        switches: -avzr --delete --exclude-from='deploy-exclude.txt'
        path: ./
        remote_path: ${{ secrets.SERVER_DIR_PUBLIC }}
        remote_host: ${{ secrets.SERVER_DESTINATION_PUBLIC }}
        remote_user: ${{ secrets.USERNAME_PUBLIC }}
        remote_key: ${{ secrets.SERVER_SSH_KEY }}
